version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Utipec2026*$'
      MYSQL_DATABASE: indicadores
    volumes:
      - mysql_data_nueva:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  mysql_data_nueva: